services:
  bootoolz:
    build:
      context: ./bootoolz-api
      dockerfile: Dockerfile
    container_name: spring-boot
    env_file:
      - .env
    volumes:
      - ./bootoolz-api:/api
    ports:
      - ${API_PORT}:${API_PORT}
    restart: unless-stopped
    networks:
      - vps
    tty: true
    stdin_open: true

  nginx-reverse-proxy:
    build:
      context: ./nginx-reverse-proxy
      dockerfile: Dockerfile
    container_name: nginx-reverse-proxy
    depends_on:
      - bootoolz
    env_file:
      - .env  
    volumes:
      - ./nginx-reverse-proxy/entrypoint.sh:/entrypoint.sh:ro
      - ./nginx-reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-reverse-proxy/scripts/:/scripts/:ro
      - ./nginx-reverse-proxy/conf.d/:/etc/nginx/conf.d/
      - ./nginx-reverse-proxy/templates/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx-reverse-proxy/templates/${PUBLIC_HOSTNAME}.template:/etc/nginx/templates/${PUBLIC_HOSTNAME}.template:ro
      - ./nginx-reverse-proxy/certbot/conf:/etc/letsencrypt
      - ./nginx-reverse-proxy/certbot/www:/var/www/certbot
    networks:
      - vps
    ports:
      - "80:80"
      - "443:443"
    entrypoint: ["/entrypoint.sh"]     
    restart: no
    tty: true
    stdin_open: true

  mongodb:
    container_name: ${MONGODB_HOST}
    image: mongo:latest
    restart: unless-stopped
    networks:
      - vps
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - ./mongodb/data:/data/db
    env_file:
      - .env  

  mongo-express:
    container_name: ${ME_HOST}
    image: mongo-express:latest
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - vps
    ports:
      - ${ME_PORT}:${ME_PORT}
    env_file:
      - .env

networks:
  vps:
    driver: bridge