services:
  nginx-reverse-proxy:
    build:
      context: ./nginx-reverse-proxy
      dockerfile: Dockerfile
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx-reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-reverse-proxy/etc/ssl/certs:/etc/ssl/certs
      - ./nginx-reverse-proxy//etc/ssl/private:/etc/ssl/private
    networks:
      - vps
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - bootoolz-api
    restart: always

  bootoolz-api:
    build:
      context: ./bootoolz-api
      dockerfile: Dockerfile
    container_name: spring-boot
    volumes:
      - ./bootoolz-api:/api
    ports:
      - "8080:8080"
    restart: always
    networks:
      - vps
    tty: true
    stdin_open: true

networks:
  vps:
    driver: bridge
