services:
  nginx-reverse-proxy:
    build:
      context: ./nginx-reverse-proxy
      dockerfile: Dockerfile
    container_name: nginx-reverse-proxy
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./nginx-reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - vps
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - bootoolz-api
    restart: unless-stopped

  bootoolz-api:
    build:
      context: ./bootoolz-api
      dockerfile: Dockerfile
    container_name: spring-boot
    volumes:
      - ./bootoolz-api:/api
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - vps
    tty: true
    stdin_open: true

volumes:
  certbot-etc:

networks:
  vps:
    driver: bridge
